kind: pipeline
name: precond-drone

steps:
  - name: precondition
    image: alpine/git
    commands:
      - "[ $(git rev-list --count HEAD) -eq 1 ] && exit 0"
      - |
        git diff --name-only HEAD~1 HEAD | \
          egrep "(^gitdiff-drone\/|^.drone.yml$)" > /dev/null || \
          exit 78

  - name: build_image
    image: stevenxie/kaniko-drone
    settings:
      context: ./precond-drone
      repo: stevenxie/precond-drone
      tags:
        - latest
        - $(cat VERSION)
      build_args:
        - VERSION=$(cat VERSION)
      username: stevenxie
      password:
        from_secret: docker_token

---

kind: pipeline
name: kaniko-drone

steps:
  - name: precondition
    image: stevenxie/precond-drone
    settings:
      pattern: kaniko-drone\/

  - name: build_program
    image: golang:1.13
    commands:
      - cd kaniko-drone
      - go mod download
      - go test -v ./...
      - CGO_ENABLED=0 go build .
    environment:
      GOPROXY: https://goproxy.io

  - name: build_image
    image: stevenxie/kaniko-drone
    settings:
      context: ./kaniko-drone
      repo: stevenxie/kaniko-drone
      tags:
        - latest
        - $(cat VERSION)
      build_args:
        - VERSION=$(cat VERSION)
      username: stevenxie
      password:
        from_secret: docker_token
      disable_gcr_helper: true

---

kind: Pipeline
name: frp

steps:
  - name: precondition
    image: stevenxie/precond-drone
    settings:
      pattern: frp\/

  - name: download
    image: busybox
    commands:
      - cd frp
      - export VERSION=$(cat VERSION)
      - |
        wget -O frp.tar.gz \
          https://github.com/fatedier/frp/releases/download/v$${VERSION}/frp_$${VERSION}_linux_amd64.tar.gz
      - tar -zxvf frp.tar.gz
      - "cp ./frp_$${VERSION}_linux_amd64/* . || :"

  - name: build
    image: stevenxie/kaniko-drone
    settings:
      context: ./frp
      repo: stevenxie/frp
      tags:
        - latest
        - $(cat VERSION)
      build_args:
        - VERSION=$(cat VERSION)
      username: stevenxie
      password:
        from_secret: docker_token

---

kind: Pipeline
name: golinter

steps:
  - name: precondition
    image: stevenxie/precond-drone
    settings:
      pattern: golinter\/

  - name: download
    image: golang:1.13
    commands:
      - |
        go get github.com/mgechev/revive && \
        mv $GOPATH/bin/revive ./golinter/revive
      - |
        go get golang.org/x/tools/cmd/goimports && \
        mv $GOPATH/bin/goimports ./golinter/goimports
    environment:
      GO111MODULE: "off"

  - name: build
    image: stevenxie/kaniko-drone
    settings:
      context: ./golinter
      repo: stevenxie/golinter
      tags:
        - latest
        - $(cat VERSION)
      build_args:
        - VERSION=$(cat VERSION)
      username: stevenxie
      password:
        from_secret: docker_token

---

kind: Pipeline
name: grpc-go

steps:
  - name: precondition
    image: stevenxie/precond-drone
    settings:
      pattern: grpc-go\/

  - name: download_protoc
    image: alpine
    commands:
      - export PROTOVERSION="$(cat ./grpc-go/PROTOVERSION)"
      - |
        wget -O /tmp/protobuf.zip \
          https://github.com/protocolbuffers/protobuf/releases/download/v$${PROTOVERSION}/protoc-$${PROTOVERSION}-linux-x86_64.zip && \
      - unzip -d /tmp /tmp/protobuf.zip
      - chmod u+x /tmp/bin/protoc
      - mv /tmp/bin/protoc ./grpc-go
      - mv /tmp/include ./grpc-go/include

  - name: download_gen
    image: golang:1.13
    commands:
      - go get github.com/golang/protobuf/protoc-gen-go
      - mv $GOPATH/bin/protoc-gen-go ./grpc-go/

  - name: build
    image: stevenxie/kaniko-drone
    settings:
      context: ./grpc-go
      repo: stevenxie/grpc-go
      tags:
        - latest
        - $(cat PROTOVERSION)
      build_args:
        - GOVERSION=$(cat GOVERSION)
      username: stevenxie
      password:
        from_secret: docker_token
